<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "media_vqf"
 *
 * Auto generated by Extension Builder 2018-01-16
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'media_vqf',
    'description' => 'Bibliothèques média de VQF',
    'category' => 'plugin',
    'author' => 'Vincent CARRASCO, Florian DE ALMEIDA, Quentin DUBRAS',
    'author_email' => 'carrascovincent8@gmail.com, florian.almeida05@gmail.com, dubrasquentin@gmail.com',
    'state' => 'alpha',
    'internal' => '',
    'uploadfolder' => '1',
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '8.7.0-8.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
